### ISSUE TITLE
why i cant build this project using webpack?

### ISSUE THREAD

**Issue by Madasamy26** [paul-pagnan/react-instant-chat#2]
In command :  webpack
the error like:
**Invalid configuration object. Webpack has been initialised using a configuration object that
 does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { mode?, amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry
?, externals?, loader?, module?, name?, node?, output?, optimization?, parallelism?, perform
ance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, re
solveLoader?, stats?, target?, watch?, watchOptions? }
   The 'debug' property was removed in webpack 2.0.0.
   Loaders should be updated to allow passing this option via loader options in module.rules
.
   Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debu
g mode:
   plugins: [
     new webpack.LoaderOptionsPlugin({
       debug: true
     })
   ]
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequ
est?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, un
knownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedC
ontextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports?
}
   -> Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.resolve.extensions[0] should not be empty.
   -> A non-empty string**

can you help me out from this??

**Comment by paul-pagnan** [comment]
Hi Maddyshien,

I can see you are attempting to use a version of Webpack greater than version 2. The package.json specifies version 1
Please try remove your node_modules and reinstall 
Unfortunately, this repo is still on webpack v1
