### ISSUE TITLE
Webhooks in the application and connected js scripts

### ISSUE THREAD

**Issue by heersheth** [paul-pagnan/react-instant-chat#3]
Hey,

I am new to react and I am looking to build a pet project which is similar to your chat app. So far I have understood the basics,  but I am not able to analyse this without the tutorial. 

I also took a look at your tutorial github code, but the CoderAcadamy link isn't working here. 

I really am keen on learning this language and your project is really inspiring me to practice more of this code. But wihtout a brief or a basic description i am not able to move forward. 
I really am not able to understand the coupling of the code. what I mean by this is If I can be told, which code is being called on which commands call in which specific file.

I hope you understand my query and help me out. 

If You really want me, I can even mail you and ask for a tutorial which will help me out greatly.

Cheers!

**Comment by paul-pagnan** [comment]
Hi there heersheth,

Sorry for the late reply, the link to the tutorial is here:
https://medium.com/@coderacademy/you-can-build-an-fb-messenger-style-chat-app-with-reactjs-heres-how-intermediate-211b523838ad

I have also updated the Readme to include this link

Hope that helps!

Thanks
Paul
